--- !ditz.rubyforge.org,2008-03-06/project 
name: twowaysql
version: "0.4"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: twowaysql
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2 release
  status: :released
  release_time: 2008-09-05 08:08:30.793430 Z
  log_events: 
  - - 2008-09-03 08:30:15.096853 Z
    - takuto <takuto.wada@gmail.com>
    - created
    - first published version.
  - - 2008-09-05 08:08:30.793446 Z
    - takuto <takuto.wada@gmail.com>
    - released
    - 0.2 release done.
- !ditz.rubyforge.org,2008-03-06/release 
  name: release_0_3
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-09-05 11:23:24.696817 Z
    - takuto <takuto.wada@gmail.com>
    - created
    - release 0.3
- !ditz.rubyforge.org,2008-03-06/release 
  name: release_0_2_1
  status: :released
  release_time: 2008-09-07 16:48:59.265076 Z
  log_events: 
  - - 2008-09-07 16:13:59.207476 Z
    - takuto <takuto.wada@gmail.com>
    - created
    - release 0.2.1
  - - 2008-09-07 16:48:59.265087 Z
    - takuto <takuto.wada@gmail.com>
    - released
    - 0.2.1 release
- !ditz.rubyforge.org,2008-03-06/release 
  name: release_0_4
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-09-10 06:27:14.808896 Z
    - takuto <takuto.wada@gmail.com>
    - created
    - ""
